#pragma once

#include "Dew.h"

class ParametersLandSurface
{
public:
    ParametersLandSurface();
    ~ParametersLandSurface();
    void SetINTER_MAX(double value);
    double GetINTER_MAX() const;
    void SetEPOT_PAR(double value);
    double GetEPOT_PAR() const;
    void SetWET_PER_CORR(double value);
    double GetWET_PER_CORR() const;
    void SetACC_TEMP(double value);
    double GetACC_TEMP() const;
    void SetMELT_TEMP(double value);
    double GetMELT_TEMP() const;
    void SetSNOW_MELT_RATE(double value);
    double GetSNOW_MELT_RATE() const;
    void SetICE_MELT_RATE(double value);
    double GetICE_MELT_RATE() const;
    void SetFREEZE_EFF(double value);
    double GetFREEZE_EFF() const;
    void SetMAX_REL(double value);
    double GetMAX_REL() const;
    void SetALBEDO(double value);
    double GetALBEDO() const;
    void SetCV_SNOW(double value);
    double GetCV_SNOW() const;
    void SetSNOW_WEIGHT(int k, double value);
    double GetSNOW_WEIGHT(int k) const;
    void SetTREE_HEIGHT(double value);
    double GetTREE_HEIGHT() const;
    void SetTREE_LAI(double value);
    double GetTREE_LAI() const;
    void SetTREE_LAI_CORR(double value);
    double GetTREE_LAI_CORR() const;
    void SetBULK_RESISTANCE(double value);
    double GetBULK_RESISTANCE() const;
    void SetALBEDO_SNOW(double value);
    double GetALBEDO_SNOW() const;
    void SetDECIDUOUS_SHARE(double value);
    double GetDECIDUOUS_SHARE() const;
    void SetWind_H(double value);
    double GetWind_H() const;
    void SetTopen_min(double value);
    double GetTopen_min() const;
    void SetTclose_min(double value);
    double GetTclose_min() const;
    void SetVPDclose(double value);
    double GetVPDclose() const;
    void SetVPDopen(double value);
    double GetVPDopen() const;
    void SetGH(double value);
    double GetGH() const;
    void SetCL(double value);
    double GetCL() const;
    void SetZ0G(double value);
    double GetZ0G() const;
    void SetGSMAX(double value);
    double GetGSMAX() const;
    void SetCR(double value);
    double GetCR() const;
    void SetD50(double value);
    double GetD50() const;
    void SetQ50(double value);
    double GetQ50() const;

private:
    double INTER_MAX;
    double EPOT_PAR;
    double WET_PER_CORR;
    double ACC_TEMP;
    double MELT_TEMP;
    double SNOW_MELT_RATE;
    double ICE_MELT_RATE;
    double FREEZE_EFF;
    double MAX_REL;
    double ALBEDO;
    double CV_SNOW;
    double SNOW_WEIGHT[numberSnowClasses];
    double TREE_HEIGHT;
    double TREE_LAI;
    double TREE_LAI_CORR;
    double BULK_RESISTANCE;
    double ALBEDO_SNOW;
    double DECIDUOUS_SHARE;
    double WIND_H;
    double Topen_min;
    double Tclose_min;
    double VPDclose;
    double VPDopen;
    double gh;
    double cl;
    double z0g;
    double gsmax;
    double CR;
    double D50;
    double Q50;
};
